// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/sample/message/user-management.proto

package com.sample.message;

public interface RetrieveUserCmdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sample.message.RetrieveUserCmd)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
