// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/sample/message/user-management.proto

package com.sample.message;

public interface UserVoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sample.message.UserVo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string userName = 2;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
