// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/sample/message/user-management.proto

package com.sample.message;

public final class UserManagement {
  private UserManagement() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sample_message_UserVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sample_message_UserVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sample_message_UserListVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sample_message_UserListVo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sample_message_CreateUserCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sample_message_CreateUserCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sample_message_UpdateUserCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sample_message_UpdateUserCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sample_message_DeleteUserCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sample_message_DeleteUserCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sample_message_RetrieveUserCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sample_message_RetrieveUserCmd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/sample/message/user-management.pro" +
      "to\022\022com.sample.message\032\037google/protobuf/" +
      "timestamp.proto\032\025scalapb/scalapb.proto\"<" +
      "\n\006UserVo\022\016\n\006userId\030\001 \001(\t\022\020\n\010userName\030\002 \001" +
      "(\t\022\020\n\010password\030\003 \001(\t\"]\n\nUserListVo\022)\n\005it" +
      "ems\030\001 \003(\0132\032.com.sample.message.UserVo\022\017\n" +
      "\007hasMore\030\002 \001(\010\022\023\n\013pagingState\030\003 \001(\t\"C\n\rC" +
      "reateUserCmd\022\016\n\006userId\030\001 \001(\t\022\020\n\010userName" +
      "\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\"C\n\rUpdateUserCm" +
      "d\022\016\n\006userId\030\001 \001(\t\022\020\n\010userName\030\002 \001(\t\022\020\n\010p" +
      "assword\030\003 \001(\t\"\037\n\rDeleteUserCmd\022\016\n\006userId" +
      "\030\001 \001(\t\"!\n\017RetrieveUserCmd\022\016\n\006userId\030\001 \001(" +
      "\tB+\n\022com.sample.messageB\016UserManagementP" +
      "\001\342?\002\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          scalapb.options.Scalapb.getDescriptor(),
        }, assigner);
    internal_static_com_sample_message_UserVo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sample_message_UserVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sample_message_UserVo_descriptor,
        new java.lang.String[] { "UserId", "UserName", "Password", });
    internal_static_com_sample_message_UserListVo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sample_message_UserListVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sample_message_UserListVo_descriptor,
        new java.lang.String[] { "Items", "HasMore", "PagingState", });
    internal_static_com_sample_message_CreateUserCmd_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sample_message_CreateUserCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sample_message_CreateUserCmd_descriptor,
        new java.lang.String[] { "UserId", "UserName", "Password", });
    internal_static_com_sample_message_UpdateUserCmd_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_sample_message_UpdateUserCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sample_message_UpdateUserCmd_descriptor,
        new java.lang.String[] { "UserId", "UserName", "Password", });
    internal_static_com_sample_message_DeleteUserCmd_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_sample_message_DeleteUserCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sample_message_DeleteUserCmd_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_sample_message_RetrieveUserCmd_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_sample_message_RetrieveUserCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sample_message_RetrieveUserCmd_descriptor,
        new java.lang.String[] { "UserId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(scalapb.options.Scalapb.options);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.TimestampProto.getDescriptor();
    scalapb.options.Scalapb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
