// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/sample/message/user-management.proto

package com.sample.message;

public interface UserListVoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sample.message.UserListVo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.sample.message.UserVo items = 1;</code>
   */
  java.util.List<com.sample.message.UserVo> 
      getItemsList();
  /**
   * <code>repeated .com.sample.message.UserVo items = 1;</code>
   */
  com.sample.message.UserVo getItems(int index);
  /**
   * <code>repeated .com.sample.message.UserVo items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.sample.message.UserVo items = 1;</code>
   */
  java.util.List<? extends com.sample.message.UserVoOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.sample.message.UserVo items = 1;</code>
   */
  com.sample.message.UserVoOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>bool hasMore = 2;</code>
   */
  boolean getHasMore();

  /**
   * <code>string pagingState = 3;</code>
   */
  java.lang.String getPagingState();
  /**
   * <code>string pagingState = 3;</code>
   */
  com.google.protobuf.ByteString
      getPagingStateBytes();
}
